substitutions:
  _REGION: us-central1
  _SERVICE: aridinsights-web
  _AR_REPO: web
  _IMAGE_NAME: aridinsights-web

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${TAG_NAME}",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${TAG_NAME}"
      ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE}",
        "--image", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${TAG_NAME}",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--quiet",
        "--labels", "release_tag=${TAG_NAME},git_sha=${COMMIT_SHA},build_id=${BUILD_ID}"
      ]

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${TAG_NAME}"
