steps:
  - name: node:20-alpine
    entrypoint: sh
    args:
      - -c
      - |
        npm ci
        npm run lint
        npm run build
    dir: apps/web-main
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
