import os
import json
import re

CURATED_DIR = "prompts/curated"
CATALOG_FILE = "prompts/catalog/prompts.json"
CATALOG_MD = "prompts/catalog/prompts.md"

def parse_metadata(content):
    meta = {}
    for line in content.split('\n'):
        if line.startswith("- **"):
            parts = line.split('**:', 1)
            if len(parts) == 2:
                key = parts[0].replace("- **", "").strip().lower()
                val = parts[1].strip()
                meta[key] = val
    return meta

def build_catalog():
    print("Building Catalog...")
    entries = []
    
    for root, dirs, files in os.walk(CURATED_DIR):
        for file in files:
            if not file.endswith(".md"): continue
            
            filepath = os.path.join(root, file)
            with open(filepath, 'r') as f:
                content = f.read()
                
            meta = parse_metadata(content)
            # Fallback if metadata missing
            if not meta.get('id'):
                meta['id'] = file
            
            meta['path'] = filepath
            meta['rel_path'] = os.path.relpath(filepath, "prompts/catalog") # relative to catalog md location
            entries.append(meta)

    # Sort by Category then ID
    entries.sort(key=lambda x: (x.get('category', 'misc'), x.get('id')))

    # Write JSON
    with open(CATALOG_FILE, 'w') as f:
        json.dump(entries, f, indent=2)
        
    # Write MD
    with open(CATALOG_MD, 'w') as f:
        f.write("# Discovered Prompts Catalog\n\n")
        f.write("Generated by `prompts/tools/prompt_catalog_build.py`\n\n")
        f.write("| Category | ID | Source | Link |\n")
        f.write("|---|---|---|---|\n")
        
        for entry in entries:
            f.write(f"| {entry.get('category', 'misc')} | {entry.get('id')} | {entry.get('source', 'unknown')} | [View]({entry['rel_path']}) |\n")
            
    print(f"Catalog rebuilt with {len(entries)} entries.")

if __name__ == "__main__":
    build_catalog()
